apiVersion: v1
kind: Pod
metadata:
  name: gke-training-pod
spec:
  containers:
  - name: tf-demo-mnist
    image: gcr.io/ndixita-test/tf_custom_container:20240314_183239
    resources:
      limits:
        cpu: 4
